name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(github.event_name == 'pull_request' && '[{"name":"nest-api"},{"name":"react-client"}]' || '[{"name":"nest-api","deploy":true},{"name":"react-client","deploy":true}]') }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - name: Lint
        run: npx nx run ${{ matrix.project.name }}:lint

      - name: Test
        run: npx nx run ${{ matrix.project.name }}:test

      - name: Build
        if: matrix.project.deploy
        run: npx nx run ${{ matrix.project.name }}:build

      - name: Deploy
        if: matrix.project.deploy
        env:
          VERCEL_TOKEN: ${{ secrets[format('VERCEL_TOKEN_{0}', matrix.project.name)] }}
        run: npx nx run ${{ matrix.project.name }}:deploy
